[tool.poetry]
name = "dz9-2"
version = "0.1.0"
description = ""
authors = ["Владислав Дранников <vlad.drannikov@mail.ru>"]
readme = "README.md"
packages = [{include = "dz9"}]

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
